# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(917, 690)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -10, 931, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 70, 741, 111))
        self.label_2.setObjectName("label_2")
        self.sifreyigoster = QtWidgets.QCheckBox(Form)
        self.sifreyigoster.setGeometry(QtCore.QRect(600, 420, 91, 21))
        self.sifreyigoster.setObjectName("sifreyigoster")
        self.girisyap = QtWidgets.QPushButton(Form)
        self.girisyap.setGeometry(QtCore.QRect(460, 490, 75, 23))
        self.girisyap.setObjectName("girisyap")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(310, 340, 265, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.kulladi = QtWidgets.QLineEdit(self.splitter)
        self.kulladi.setObjectName("kulladi")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(390, 410, 181, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        self.label_4.setObjectName("label_4")
        self.sifre = QtWidgets.QLineEdit(self.splitter_2)
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifre.setObjectName("sifre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">İNÖNÜ ÜNİVERSİTESİ GÜVENLİK SİSTEMİ</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">GİRİŞ SAYFASI</span></p></body></html>"))
        self.sifreyigoster.setText(_translate("Form", "Şifreyi Göster"))
        self.girisyap.setText(_translate("Form", "Giriş Yap"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Kullanıcı Adı :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Şifre :</span></p></body></html>"))
