# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misafirgiris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1067, 760)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1111, 791))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Adsız.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.goruntu = QtWidgets.QGraphicsView(Form)
        self.goruntu.setGeometry(QtCore.QRect(20, 90, 421, 421))
        self.goruntu.setObjectName("goruntu")
        self.fotografcek = QtWidgets.QPushButton(Form)
        self.fotografcek.setGeometry(QtCore.QRect(340, 520, 81, 23))
        self.fotografcek.setObjectName("fotografcek")
        self.aracgoruntu = QtWidgets.QGraphicsView(Form)
        self.aracgoruntu.setGeometry(QtCore.QRect(610, 90, 431, 421))
        self.aracgoruntu.setObjectName("aracgoruntu")
        self.aracsec = QtWidgets.QPushButton(Form)
        self.aracsec.setGeometry(QtCore.QRect(950, 520, 91, 31))
        self.aracsec.setObjectName("aracsec")
        self.icerial = QtWidgets.QPushButton(Form)
        self.icerial.setGeometry(QtCore.QRect(470, 660, 75, 31))
        self.icerial.setObjectName("icerial")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(376, 20, 321, 41))
        self.label_6.setObjectName("label_6")
        self.kaydet = QtWidgets.QPushButton(Form)
        self.kaydet.setGeometry(QtCore.QRect(170, 710, 75, 31))
        self.kaydet.setObjectName("kaydet")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(620, 580, 184, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.plaka = QtWidgets.QLineEdit(self.splitter)
        self.plaka.setObjectName("plaka")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setGeometry(QtCore.QRect(100, 590, 171, 20))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        self.label_4.setObjectName("label_4")
        self.isim = QtWidgets.QLineEdit(self.splitter_3)
        self.isim.setObjectName("isim")
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setGeometry(QtCore.QRect(80, 630, 191, 20))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_5 = QtWidgets.QLabel(self.splitter_4)
        self.label_5.setObjectName("label_5")
        self.soyisim = QtWidgets.QLineEdit(self.splitter_4)
        self.soyisim.setObjectName("soyisim")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(30, 670, 241, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setObjectName("label_3")
        self.ziyaretsebebi = QtWidgets.QLineEdit(self.splitter_2)
        self.ziyaretsebebi.setObjectName("ziyaretsebebi")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fotografcek.setText(_translate("Form", "Fotoğraf Çek"))
        self.aracsec.setText(_translate("Form", "Girecek Aracı Seç"))
        self.icerial.setText(_translate("Form", "İçeri Al"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">MİSAFİR GİRİŞİ</span></p></body></html>"))
        self.kaydet.setText(_translate("Form", "Kaydet"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Plaka :</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">İsim :</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Soyisim :</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ziyaret Sebebi :</span></p></body></html>"))
